# Generated by Django 5.2.8 on 2025-11-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='image',
            field=models.CharField(default='https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExZDViaXlpMWc1N2ttODhqaXV2b3Z2eHgwdzdkMTVzcXduMTAyYjdzbSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/84ZzhsJZWlE3e/giphy.gif', max_length=1000),
        ),
    ]
